### PR TITLE
fix: remove superfluous negentropy link

### PR DESCRIPTION
**Pull request by SionoiS**
@NagyZoltanPeter noticed some weird behavior for negentropy bindings. I removed this line that was a remnant of the old bindings.

### CODE REVIEW

**Review by Ivansete-status — APPROVED** [review]

**Comment by NagyZoltanPeter** [comment]
Honestly with my try on same change still got weird error of missing references while building docker image....

**Comment by SionoiS** [comment]
> Honestly with my try on same change still got weird error of missing references while building docker image....

I did too but then it magically resolved itself after a couple tries... :shrug:  At least we know it's superfluous?

**Review by gabrielmer — APPROVED** [review]
Thank you!

**Comment by NagyZoltanPeter** [comment]
@SionoiS : This can be closed without merge. My PR that made negentropy static linked overrides this.

**Pull request closed without merging**
