### PR TITLE
chore: vacuum in time based retention policy

### PR DESCRIPTION
**Pull request by ABresting**
# Description
Enables the vacuum of DB in Time-based retention policy. 

# Changes

- [x] vacuuming of DB in time-based retention policy

## Issue

#2164

### CODE REVIEW

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks for that @ABresting !
Would it be possible to test that this actually reduces the sqlite file size?
Cheers

**Review by SionoiS — APPROVED** [review]
Approved BUT like Ivan said. Are we sure it works?

**Comment by ABresting** [comment]
> Approved BUT like Ivan said. Are we sure it works?

Now that's actually a `good first issue` material!

**Review by jm-clius — APPROVED** [review]
Approving, although I think we have to monitor how long this vacuuming can stall nodes with large DBs (e.g. Status with 30 days of history), or do we already have data on how long a vacuum can take?

**Comment by richard-ramos** [comment]
Would be good to test this PR with a copy of a database like status.test or status.prod. I'm worried that this will end up impacting negatively the node. `VACUUM` seems more of an activity that should be executed by infra periodically by taking the node offline than something that could be executed as part of normal operation of the node

**Comment by richard-ramos** [comment]
The go-waku prod fleet is currently connected to status.prod and keeps 7d of history. VACUUM took 11mins to execute, (because of this, this PR was introduced to indicate the user that something is happening https://github.com/waku-org/go-waku/pull/838)
cc: @yakimant

**Comment by jm-clius** [comment]
I agree with @richard-ramos here. Approved previously, but with some hard numbers of time it takes to vacuum, I don't think this is a good idea. @ABresting @Ivansete-status I'm not sure that periodic vacuuming should be part of retention policy at all - this seems to be something specifically required by SQLite and not any other type of backend. In this case a better approach is indeed to have infra perform the vacuum "out of band" from time to time so as not to stall production nodes. In our case, this is only necessary until the migration to postgresql, which should be imminent.

**Comment by Ivansete-status** [comment]
Good point indeed!
Thanks for bringing this @richard-ramos !

How long does it take if you perform _VACUUM_ regularly? For example, daily, or two consecutive _VACUUM_ calls? I have the impression that it took 11' because the vacuum operation needed to handle a lot of data.

I believe that the _VACUUM_ concept is widely used in other backends. In _Postgres_, the "standard" _VACUUM_ operation doesn't necessarily block other operations (see [this](https://www.postgresql.org/docs/current/routine-vacuuming.html#VACUUM-BASICS).) And we are performing it asynchronously.

Finally, if we decide that the _VACUUM_ operation should be made manually, then we will need to adapt the other retention policies (capacity and size.) as well.

CC: @NagyZoltanPeter @apentori

**Comment by Ivansete-status** [comment]
Thanks for checking @richard-ramos , @yakimant !
Wow, it is super slow!

In this case, even though this PR is approved we can't merge it @ABresting. I think we need to close this PR and submit a different one where we remove the `VACUUM` calls from the "capacity" and "size" retention policies. We cannot perform VACUUM when working with _SQLite_. There shouldn't be issues in _Postgres_ because all is async there.

On the other hand, we need to create a separate chron script to perform the vacuum task separately under certain conditions. WDYT @richard-ramos , @yakimant ?

**Comment by yakimant** [comment]
I have simmilar feelings, we need to address sqlite vacuuming differently.
Either by cron job or https://sqlite.org/pragma.html#pragma_auto_vacuum, but not a part of waku code.

**Comment by richard-ramos** [comment]
I'm actually thinking of removing the vacuum functionality of go-waku because seems to me that having it as part of the node is too problematic.

**Comment by ABresting** [comment]
closing this PR since due to SQLite it is better to not use automatic vacuuming.

**Pull request closed without merging**
