### PR TITLE
chore: updating TWN bootstrap fleet to waku.sandbox

### PR DESCRIPTION
**Pull request by gabrielmer**
# Description
Changing TWN bootstrap fleet to `waku.sandbox` which will be our stable "prod" fleet

### CODE REVIEW

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks! :100:

**Comment by alrevuelta** [comment]
Meta comment but if

> "waku.sandbox which will be our stable "prod" fleet"

Perhaps that fleet should have a better name, eg `waku.twn` or `waku.prod`.

**Review by jm-clius — APPROVED** [review]

**Comment by gabrielmer** [comment]
> Meta comment but if
> 
> > "waku.sandbox which will be our stable "prod" fleet"
> 
> Perhaps that fleet should have a better name, eg `waku.twn` or `waku.prod`.

Agreed! Not sure how the `sandbox` name was chosen but it doesn't describe much

**Comment by Ivansete-status** [comment]
Morning all!
@gabrielmer , @alrevuelta - re the fleet's name, we had some discussions and concluded that it was not correct to consider this fleet as some kind of "prod" fleet.

See: 
 - https://discord.com/channels/1110799176264056863/1201935816084181063/1201939010755240056
   image

and
  - https://discord.com/channels/1110799176264056863/1217775665370234921/1217800276032098345
  image

**Pull request merged**
