### PR TITLE
chore: merge release/v0.30 into master

### PR DESCRIPTION
**Pull request by Ivansete-status**
# Description
We are adding the recent RLN_V2 changes into `master` so that we can benefit from that.

### CODE REVIEW

**Comment by rymnc** [comment]
Not sure if I'm missing something, shouldn't the diff be much larger?

**Comment by Ivansete-status** [comment]
> ~Not sure if I'm missing something, shouldn't the diff be much larger?~ looks like this commit is duplicated [a02832f](https://github.com/waku-org/nwaku/commit/a02832fe1296d2deb8d8c874fb13287cbc3ec143) in this branch and master, no worries though

This happens because I had to fix some minor conflicts. Then, I resolved them from _GitHub_ and that a merge from `master` into `release/v0.30`:

image

If you want to see the changes better I suggest comparing the versions: https://github.com/waku-org/nwaku/compare/v0.29.0...v0.30.0

**Comment by rymnc** [comment]
> @rymnc - I reverted the commit where I solved the small conflicts so that you can see them and see the effect of resolving them :) Ping me if you want to make it together

no worries, please go ahead!t

**Comment by Ivansete-status** [comment]
I'm closing this PR because that will mess up the `release/v0.30` branch.
Instead, the following PR is considered to bring the `release/v0.30` changes into `master`: https://github.com/waku-org/nwaku/pull/2866

**Pull request closed without merging**
