### PR TITLE
chore: archive.nim - increase the max limit of content topics per query to 100

### PR DESCRIPTION
**Pull request by Ivansete-status**
### Description
The _Status_ app tend to perform _Store_ queries multiple content topics. In this tiny PR we are increasing the max number of content topics in a query from 10 to 100

cc @chaitanyaprem

### CODE REVIEW

**Comment by chaitanyaprem** [comment]
cc @richard-ramos

**Review by NagyZoltanPeter — APPROVED** [review]
Legit! 
My only concern that such amount of content_topics will not work on REST interface because of URL max length... although it is not a major consideration.

**Review by gabrielmer — APPROVED** [review]
Thanks so much!

**Review by richard-ramos — APPROVED** [review]
I like this PR, but, I'm wondering, what was the reason behind using 10 content topics as a max?

**Review by chaitanyaprem — APPROVED** [review]
LGTM

**Comment by Ivansete-status** [comment]
> I like this PR, but, I'm wondering, what was the reason behind using 10 content topics as a max?

Good question but I can't quite remember the original reasons ( cc @SionoiS )

**Pull request merged**
