### PR TITLE
chore: add epic and link feature_request.md

### PR DESCRIPTION
**Pull request by Ivansete-status**
# Description
This is meant to help align the new feature issues that we create with the existing epics. Notice that each Epic, in turn, should be under a certain Deliverable.

### CODE REVIEW

**Review by darshankabariya — APPROVED** [review]
Thanks ! LGTM :)

**Review by gabrielmer — APPROVED** [review]
Graciass

**Review by NagyZoltanPeter — APPROVED** [review]
Ok, cool!

**Comment by Ivansete-status** [comment]
Hey @chair28980 !
We are about to add "epic link" field in the feature-issue template. Is this the correct way or there is another approach of achieving the same result but more aligned with other teams?

**Comment by chair28980** [comment]
@Ivansete-status the `epic link` will be helpful.

Github supports linking back to a parent issue at the top of the issue as such:

Screenshot 2024-06-18 at 2 46 29 PM

To achieve this you must have an ordered checkbox list in the parent issue that lists the issue as such:

Screenshot 2024-06-18 at 2 48 04 PM

This is how the Deliverable > Epic > Task parent-child relationship is structured.

I do think that including a field for `Epic Link` will be helpful to whoever is creating the issue.

**Pull request merged**
