### PR TITLE
feat(rlnv2): rlnv2 fork feature branch  [dont merge]

### PR DESCRIPTION
**Pull request by rymnc**
# Description

This PR will be used as a feature branch for the upcoming rln-v2 fork.

Pending PRs to be merged into it -
- [x] #2770 
~~- [ ] remove tree sync and replace with merkle proof and root getters from the new contract~~
- [x] https://github.com/waku-org/nwaku/pull/2782

# Changes

- [x] only use rln-v2, remove references of rln-v1
- [x] updated contract interface

## Issue

Addresses #2758

### CODE REVIEW

**Comment by alrevuelta** [comment]
Thanks, looks good.

**Review by Ivansete-status — COMMENTED** [review]
LGTM! Thanks! :100: 
I'm not approving it because we won't merge it yet :)

**Review by alrevuelta — APPROVED** [review]
lgtm. great work on this thanks.

**Comment by rymnc** [comment]
@Ivansete-status can we merge now?

**Comment by rymnc** [comment]
closing in favor of https://github.com/waku-org/nwaku/pull/2828

**Pull request closed without merging**
