### PR TITLE
chore: Update CHANGELOG.md to reflect bug fix for issue #2317

### PR DESCRIPTION
**Pull request by Ivansete-status**
# Description
Update CHANGELOG.md to reflect the latest `v0.23.1` version created.

### CODE REVIEW

**Review by gabrielmer — COMMENTED** [review]
I think we have to change this date

**Review by gabrielmer — COMMENTED** [review]
it's missing the metadata protocol here, it appears in the footer of 0.23.0
https://github.com/waku-org/nwaku/blob/e30a024480bbe46d275ebc379b08f3bb541c6d5b/CHANGELOG.md?plain=1#L13-L19

**Review by SionoiS — APPROVED** [review]
:+1: thanks

**Review by gabrielmer — APPROVED** [review]
Thanks so much! 🤩

**Pull request merged**
