### PR TITLE
chore: postgres_driver.nim - rename table's name from "messages" to "message"

### PR DESCRIPTION
**Pull request by Ivansete-status**
# Description
Simple PR where we rename the _Postgres_ table to a more idiomatic name for relational databases.

## Issue

https://github.com/waku-org/nwaku/issues/1842

### CODE REVIEW

**Review by gabrielmer — APPROVED** [review]
Looks great! Thank you! :)

**Review by NagyZoltanPeter — APPROVED** [review]
It's fine, thank you.

**Review by ABresting — APPROVED** [review]

**Comment by jakubgs** [comment]
As far as I can tell this broke `shards.test` fleet:
```
ERR 2023-10-06 07:29:39.164+00:00 4/7 Mounting protocols failed              topics="wakunode main" tid=1 file=wakunode2.nim:85 error="failed to setup archive driver: error creating table: error in createMessageTable: rowsRes is err in exec: error in rows: ERROR:  relation \"messageindex\" already exists\n"
```
Endless restart loop.

**Comment by jakubgs** [comment]
I have built https://github.com/waku-org/nwaku/commit/12e8b122 - which is the preiovus commit - here:
https://ci.infra.status.im/job/nim-waku/job/deploy-shards-test/14/

And it works:
```
admin@store-01.ac-cn-hongkong-c.shards.test:~ % d
CONTAINER ID   NAMES            IMAGE                              CREATED              STATUS
e2f30b5bbb7f   nim-waku-store   wakuorg/nwaku:deploy-shards-test   About a minute ago   Up About a minute (healthy)
```

**Pull request merged**
