### PR TITLE
chore: Copy back from nwaku-compose - an enhanced version of convenient node health check script

### PR DESCRIPTION
**Pull request by NagyZoltanPeter**
Follow up PR on nwaku-compose https://github.com/waku-org/nwaku-compose/pull/86

This enhancement to the script handles more edge cases and prints accordingly.

### CODE REVIEW

**Review by SionoiS — APPROVED** [review]
LGTM but do we really need a health script?

The rest /health endpoint should be easy enough to use in nwaku no?

**Comment by NagyZoltanPeter** [comment]
> LGTM but do we really need a health script?
> 
> The rest /health endpoint should be easy enough to use in nwaku no?

Haha, check out node-help channel sometimes...
It's easier to tell anyone to run that script.

**Comment by SionoiS** [comment]
> > LGTM but do we really need a health script?
> > The rest /health endpoint should be easy enough to use in nwaku no?
> 
> Haha, check out node-help channel sometimes... It's easier to tell anyone to run that script.

Yeah that's fair. :rofl:

**Review by gabrielmer — APPROVED** [review]
LGTM, thanks so much!

**Pull request merged**
