### PR TITLE
chore(rln-relay): logs, updated submodule, leaves_set metric

### PR DESCRIPTION
**Pull request by rymnc**
# Description

This PR includes very minor changes to improve qol

# Changes

- [x] logging from `fromBlock` while syncing
- [x] updated zerokit submodule to `v0.3.3`
- [x] updated metric logging for memberships 

### Note

To make sure you don't get errors while linking `librln.a`, remove the file from the project root

### CODE REVIEW

**Review by vpavlin — APPROVED** [review]

**Review by alrevuelta — APPROVED** [review]
lgtm!

**Comment by alrevuelta** [comment]
@vpavlin does the bot post the correct "Built from https://github.com/waku-org/nwaku/commit/4617f6e204ec32072035042347f55da630cbddfd"? Commit is 02799fed008f6035fb0af1ff4b4628250b48bcc6, so seems there is a missmatch, or?

**Comment by rymnc** [comment]
@vpavlin is it okay if we merge this after the release tomorrow/?

**Comment by vpavlin** [comment]
> @vpavlin does the bot post the correct 

Yes and no, it seems like it is merging the PR to the master and building it, which results in different commit in local checkout than where it built from (at least I think that's what is happening?). Will need to look into how to get the actual commit hash again, sorry about this..

**Comment by vpavlin** [comment]
> @vpavlin is it okay if we merge this after the release tomorrow/?

It's fine, unless it should be part of the release? We are still waiting for #2031, to prevent the DB issues

**Pull request merged**
