### PR TITLE
chore: removing protected-topic cli flag

### LINKED ISSUE #2984: chore: remove protectedTopic config item
As part of our plan to remove the pubsub topic configuration, we are also switching the protected topics feature in favor of protected shards.

The PR with the deprecation notice is https://github.com/waku-org/nwaku/pull/2983 , which will enter `v0.32.0`.

This issue tracks the removal of the protected topics configuration, which should happen for the release `v0.34.0`

### PR DESCRIPTION
**Pull request by gabrielmer**
# Description
Removing protected-topic CLI flag

## Issue

closes #2984

### CODE REVIEW

**Review by Ivansete-status — COMMENTED** [review]
I'd like to clean this up too but I think we need to perform some previous work to adapt the current `status` fleets' configurations and maybe use `protected-shards` instead:
https://github.com/status-im/infra-status/blob/d319a1e405cdf1ca18b60d2a2fd19ff629d18194/ansible/group_vars/store.yml#L30-L33

**Comment by gabrielmer** [comment]
> I'd like to clean this up too but I think we need to perform some previous work to adapt the current `status` fleets' configurations and maybe use `protected-shards` instead: https://github.com/status-im/infra-status/blob/d319a1e405cdf1ca18b60d2a2fd19ff629d18194/ansible/group_vars/store.yml#L30-L33

Ooh good catch! I think it's just a matter of adding the new variable to the infra repo and use the new format, shouldn't be an issue I think. Or is there a longer process to follow?

**Review by NagyZoltanPeter — APPROVED** [review]
LGTM

**Comment by gabrielmer** [comment]
Infra changes are ready:
- https://github.com/status-im/infra-role-nim-waku/pull/36
- https://github.com/status-im/infra-status/pull/51
- https://github.com/status-im/infra-waku/pull/30

**Review by Ivansete-status — APPROVED** [review]
Awesome! Thanks for it!

**Pull request merged**
