### PR TITLE
feat(coverage): Add simple coverage

### PR DESCRIPTION
**Pull request by AlejandroCabeza**
# Description
Implement a coverage script that runs all tests and generates the coverage report.

# Changes
- [X] Implement coverage script
- [X] Add aggregating files under all tests directories that run all test files in that directory.

### CODE REVIEW

**Comment by vpavlin** [comment]
@AlejandroCabeza Something is wrong with the script - this is the output I get

```
$ ./scripts/run_cov.sh 
Hint: used config file '/home/vpavlin/.choosenim/toolchains/nim-1.6.14/config/nim.cfg' [Conf]
Hint: used config file '/home/vpavlin/.choosenim/toolchains/nim-1.6.14/config/config.nims' [Conf]
Hint: used config file '/home/vpavlin/devel/github.com/waku-org/nwaku/config.nims' [Conf]
Hint: used config file '/home/vpavlin/devel/github.com/waku-org/nwaku/tests/nim.cfg' [Conf]
.................................................................
/home/vpavlin/devel/github.com/waku-org/nwaku/tests/test_all.nim(1, 2) Error: cannot open file: ""
./scripts/run_cov.sh: 36: /home/vpavlin/devel/github.com/waku-org/nwaku/tests/test_all: not found
Capturing coverage data from .
Subroutine read_intermediate_text redefined at /usr/bin/geninfo line 2637.
Subroutine read_intermediate_json redefined at /usr/bin/geninfo line 2669.
Subroutine intermediate_text_to_info redefined at /usr/bin/geninfo line 2717.
Subroutine intermediate_json_to_info redefined at /usr/bin/geninfo line 2806.
Subroutine get_output_fd redefined at /usr/bin/geninfo line 2886.
Subroutine print_gcov_warnings redefined at /usr/bin/geninfo line 2914.
Subroutine process_intermediate redefined at /usr/bin/geninfo line 2944.
Found gcov version: 12.3.0
Using intermediate gcov format
Using JSON module JSON::PP
Scanning . for .gcda files ...
geninfo: WARNING: no .gcda files found in . - skipping!
Finished .info-file creation
Reading data file /home/vpavlin/devel/github.com/waku-org/nwaku/tests/test_all.info
genhtml: ERROR: no valid records found in tracefile /home/vpavlin/devel/github.com/waku-org/nwaku/tests/test_all.info
```

**Comment by AlejandroCabeza** [comment]
> @AlejandroCabeza Something is wrong with the script - this is the output I get
> 
> ```
> $ ./scripts/run_cov.sh 
> Hint: used config file '/home/vpavlin/.choosenim/toolchains/nim-1.6.14/config/nim.cfg' [Conf]
> Hint: used config file '/home/vpavlin/.choosenim/toolchains/nim-1.6.14/config/config.nims' [Conf]
> Hint: used config file '/home/vpavlin/devel/github.com/waku-org/nwaku/config.nims' [Conf]
> Hint: used config file '/home/vpavlin/devel/github.com/waku-org/nwaku/tests/nim.cfg' [Conf]
> .................................................................
> /home/vpavlin/devel/github.com/waku-org/nwaku/tests/test_all.nim(1, 2) Error: cannot open file: ""
> ./scripts/run_cov.sh: 36: /home/vpavlin/devel/github.com/waku-org/nwaku/tests/test_all: not found
> Capturing coverage data from .
> Subroutine read_intermediate_text redefined at /usr/bin/geninfo line 2637.
> Subroutine read_intermediate_json redefined at /usr/bin/geninfo line 2669.
> Subroutine intermediate_text_to_info redefined at /usr/bin/geninfo line 2717.
> Subroutine intermediate_json_to_info redefined at /usr/bin/geninfo line 2806.
> Subroutine get_output_fd redefined at /usr/bin/geninfo line 2886.
> Subroutine print_gcov_warnings redefined at /usr/bin/geninfo line 2914.
> Subroutine process_intermediate redefined at /usr/bin/geninfo line 2944.
> Found gcov version: 12.3.0
> Using intermediate gcov format
> Using JSON module JSON::PP
> Scanning . for .gcda files ...
> geninfo: WARNING: no .gcda files found in . - skipping!
> Finished .info-file creation
> Reading data file /home/vpavlin/devel/github.com/waku-org/nwaku/tests/test_all.info
> genhtml: ERROR: no valid records found in tracefile /home/vpavlin/devel/github.com/waku-org/nwaku/tests/test_all.info
> ```

Interesting, did you have `env.sh` loaded? As in `source env.sh`, I mean.

**Comment by vpavlin** [comment]
Yeah, that works, the report is being generated.

**Review by vpavlin — APPROVED** [review]
LGTM! Thanks for this

**Pull request merged**
