### PR TITLE
chore(tests): moved common test suites to its own folder

### PR DESCRIPTION
**Pull request by LNSD**
Tests suite structure should match (more or less) the project structure high-level modules (e.g., `waku/common`, `waku/v1`, `waku/v2`, `apps/wakunode2`, `apps/wakubridge`, etc.).

- [x] Moved the tests into the `common` test suite folder.
- [x] Added a suite file to run all the tests as a single test unit (see: `all_tests_common.nim`). 

For now, the idea is to keep executing these tests with the `make test2` target.

### CODE REVIEW

**Review by alrevuelta — APPROVED** [review]
Since we dont have a `make testcommon` I wouldn't add a new file `all_tests_common.nim`. Perhaps just the following in `all_tests_v2`.

```
import
  ./common/test_envvar_serialization,
  ./common/test_confutils_envvar,
  ./common/test_sqlite_migrations

...
```

But just as a suggestion, otherwise lgtm!

**Review by rymnc — APPROVED** [review]
LGTM

**Comment by LNSD** [comment]
> Since we dont have a `make testcommon` I wouldn't add a new file `all_tests_common.nim`. Perhaps just the following in `all_tests_v2`.
> 
> ```
> import
>   ./common/test_envvar_serialization,
>   ./common/test_confutils_envvar,
>   ./common/test_sqlite_migrations
> 
> ...
> ```
> 
> But just as a suggestion, otherwise lgtm!

Sure, I have a follow up PR that does exactly that.

**Review by jm-clius — APPROVED** [review]

**Comment by LNSD** [comment]
> > Since we dont have a `make testcommon` I wouldn't add a new file `all_tests_common.nim`. Perhaps just the following in `all_tests_v2`.
> > ```
> > import
> >   ./common/test_envvar_serialization,
> >   ./common/test_confutils_envvar,
> >   ./common/test_sqlite_migrations
> > 
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But just as a suggestion, otherwise lgtm!
> 
> Sure, I have a follow up PR that does exactly that.

I just had to rebase the PR 😉

**Pull request merged**
