### PR TITLE
chore: remove Waku v1 and wakubridge code

### PR DESCRIPTION
**Pull request by jm-clius**
# Description

This PR addresses the bulk of the changes necessary for https://github.com/waku-org/nwaku/issues/1767.

It removes the legacy Waku ("Waku v1") and Waku v1 <> v2 bridge ("Waku Bridge") code from the nwaku repo.
This touches a great many files, so I'll try to give reviewers some context about possible impact(s) under `Changes`.

The Waku v1 code is now maintained in https://github.com/waku-org/waku-legacy.
The Waku bridge code is now maintained in https://github.com/waku-org/waku-bridge.
Note that the `waku-bridge` repo requires some of the changes in this PR to be fully functional with working CI, although all necessary code has been moved. `waku-legacy` repo is complete, with functioning CI if any changes are to be made in future.

## Scope of changes

- [x] move all v1 code, examples and tests to [waku-legacy](https://github.com/waku-org/waku-legacy)
- [x] move all bridge code, examples and tests to [waku-bridge](https://github.com/waku-org/waku-bridge)
- [x] updated READMEs to reflect changes
- [x] NB: remove `wakunode1` from the release artifacts. From now one we won't include `wakunode1` in releases.
- [x] NB: removed all `wakunode1` and `wakubridge` build tasks from the Makefile. This will affect Jenkins deployment jobs, such as https://ci.infra.status.im/job/nim-waku/job/deploy-bridge-test/, https://ci.infra.status.im/job/nim-waku/job/deploy-bridge-prod/ and https://ci.infra.status.im/job/nim-waku/job/deploy-wakuv1-test/
- [x] Most NB: removed support for "v1" type payload encryption and decryption in nwaku, including removing the Private API from the JSON-RPC Relay API. This is potentially the most impactful change and would have to be reviewed with stakeholders before merging. Afaik this functionality is not used and not currently being planned anywhere. In order to keep this, the legacy waku code would have to be added as another submodule in `nwaku`, which I'd like to avoid if possible

## What is excluded from scope?

Removing references to `v2`, e.g. changing import paths from `waku/v2` to just `waku/`. This would clutter this PR even more, so will be done in a subsequent step.

## What should be reviewed?

The impact of items marked as "NB" under `Scope of Changes` and any other high-impact consequences of removing v1 code that I might have missed.

### CODE REVIEW

**Review by richard-ramos — APPROVED** [review]
image
:1st_place_medal:

**Review by SionoiS — APPROVED** [review]
LGTM!

Do we keep track of who use what API somewhere?

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks for this!
In the future, I think we should delete any reference to "v2" or "2" (e.g. `wakunode2`)

Also, I'd remove the 'v1' and 'v2' folders and put all the content underneath 'v2' right under the 'waku' folder, and just mention that in the `CHANGELOG.md`.
image

**Review by alrevuelta — APPROVED** [review]
@jm-clius thanks for this!!

**Pull request merged**
