### PR TITLE
fix(rln-relay): sync from a recent block number, not 0

### PR DESCRIPTION
**Pull request by rymnc**
!WIP!
- fix(rln-relay): sync from a recent block number, not 0

# Description

# Changes

- [ ] ...
- [ ] ...

### CODE REVIEW

**Comment by rymnc** [comment]
This PR is no longer required since it was fixed with the decay introduction in https://github.com/waku-org/nwaku/pull/1858

**Comment by alrevuelta** [comment]
can see its closed but out of curiosity. which block is it used to sync the registration events? from 0?

**Comment by rymnc** [comment]
> can see its closed but out of curiosity. which block is it used to sync the registration events? from 0?

Yes, as of now, its 0 - but when `waku-org/waku-rln-contract` is a submodule, we will fetch from the block number in which the contract was deployed

**Comment by alrevuelta** [comment]
@rymnc Leaving the idea in case you find it useful. afaik in solidity you can access the block `block.number`. So in the constructor that is called on deployment, just store `block.number` and then add a getter to it.

So then we can just `getDeployedBlockNumber()` and sync from there.

Is that what you had in mind by "we will fetch from the block number in which the contract was deployed" ?

**Comment by rymnc** [comment]
Sure, we can add block.number in the constructor, it's unnecessary storage though. (open to this solution)
by 
"we will fetch from the block number in which the contract was deployed", i meant from the deployment stored in the `deployments` directory in waku-org/waku-rln-contract

**Comment by alrevuelta** [comment]
> it's unnecessary storage though

shouldn't be expensive, just one variable? isnt it neglectable?

> i meant from the deployment stored in the deployments directory in waku-org/waku-rln-contract

but how will people access it? manually? or how can this be automated?

**Comment by rymnc** [comment]
> shouldn't be expensive, just one variable? isnt it neglectable?

agree, it can be neglected - I'll make the changes upstream for this 

> but how will people access it? manually? or how can this be automated?

since it is a submodule in nwaku, it will be automated - check [#1884](https://github.com/waku-org/nwaku/pull/1884), where its automatically fetched

**Comment by alrevuelta** [comment]
> since it is a submodule in nwaku, it will be automated - check https://github.com/waku-org/nwaku/pull/1884, where its automatically fetched

ah i see. but then if someone deploys its own rln contract, this wont work, and we would need a flag to specify it and override the default?

**Comment by rymnc** [comment]
> > since it is a submodule in nwaku, it will be automated - check #1884, where its automatically fetched
> 
> ah i see. but then if someone deploys its own rln contract, this wont work, and we would need a flag to specify it and override the default?

Correct - I will use your approach moving forward, but there still may be some merit in using waku-rln-contract as a submodule, wdyt?

**Comment by alrevuelta** [comment]
> but there still may be some merit in using waku-rln-contract as a submodule, wdyt?

having the ABI is needed i guess? so that would be a merit.

**Comment by rymnc** [comment]
`nim-web3` doesn't need the ab I believe ~ it wouldn't be too useful for nwaku except for using the deployedBytecode from the artifacts (but thats only for tests)

**Pull request closed without merging**
