### PR TITLE
chore(maintenance): Bumping some vendors

### PR DESCRIPTION
**Pull request by Ivansete-status**
# Description
The next vendors are being bumped:

dnsclient.nim
nim-bearssl
nim-eth
nim-faststreams
nim-http-utils
nim-json-rpc
nim-json-serialization
nim-libbacktrace
nim-metrics
nim-regex
nim-secp256k1
nim-stint
nim-testutils

## Issue
https://github.com/waku-org/nwaku/issues/2041

### CODE REVIEW

**Comment by Ivansete-status** [comment]
Notice that the ci that is failing, also fails in another PR. Therefore, it is not related to the changes proposed here.

**Comment by vpavlin** [comment]
Would it make sense to run a simulation from this PR and see if any unexpected errors show up in logs?

**Comment by Ivansete-status** [comment]
> Would it make sense to run a simulation from this PR and see if any unexpected errors show up in logs?

Yes, very good point. The idea that I had was to check if errors occur in the `wakuv2.test` fleet once this is merged.

**Review by jm-clius — APPROVED** [review]
Thanks for this!

**Pull request merged**
