### PR TITLE
chore: log messageHash for lightpush request received

### PR DESCRIPTION
**Pull request by chaitanyaprem**
# Description
While debugging message loss issues with status, had noticed that messageHash is not logged for lightpush which helps in debugging to know if message is received by the fleet nodes.

# Changes

- [x] Added messageHash to be logged while handling lightpush request.

Note: Tested by using a go-waku lightpush client to ensure messageHash is logged properly

### CODE REVIEW

**Review by gabrielmer — APPROVED** [review]
Amazing! Thanks so much! 🤩

**Review by SionoiS — APPROVED** [review]
Thank you!

**Comment by chaitanyaprem** [comment]
js CI seems to be failing? 
I doubt my log change would have caused any issue. Shall i go ahead and merge this?

**Comment by gabrielmer** [comment]
> js CI seems to be failing? I doubt my log change would have caused any issue. Shall i go ahead and merge this?

Yes! Please go ahead and merge :)
js CI has been failing for quite some time, it's definitely not related to your change

**Pull request merged**
