### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by omahs**
fix typos

### CODE REVIEW

**Review by vpavlin — APPROVED** [review]
Amazing! Thank you so much!

**Comment by alrevuelta** [comment]
@vpavlin build-docker-image ci is failing. doesnt seem related, any idea?

**Review by Ivansete-status — APPROVED** [review]

**Comment by Ivansete-status** [comment]
Hey @omahs !
Thanks so much indeed for the contribution!
When you have some spare time, kindly perform `Squash and merge` so that your changes can be applied :partying_face:

**Comment by omahs** [comment]
@Ivansete-status Hey, sorry I messed up my branch. I opened another squashed PR here: https://github.com/waku-org/nwaku/pull/2232

**Pull request closed without merging**
