### PR TITLE
chore(Makefile): Small addon to be able to list all possible target in our Makefile

### PR DESCRIPTION
**Pull request by NagyZoltanPeter**
Just a small addon, was useful for me initially (idea coming from how cmake generates Makefiles).
I hope it is still useful for others.

### CODE REVIEW

**Comment by vpavlin** [comment]
What is the difference between this and the built-in shell completion? It seems to output the same list of targets:)

**Comment by NagyZoltanPeter** [comment]
> What is the difference between this and the built-in shell completion? It seems to output the same list of targets:)

The difference is in my lack of knowledge having such feature :-D
So in this case we may can drop this one.

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks for it!

**Comment by jm-clius** [comment]
If I understand correctly we should close without merging as the feature already exists? @NagyZoltanPeter please go ahead and do so, if that is the case.

**Comment by Ivansete-status** [comment]
Yes, we can close it. I didn't know that feature too xD
Very useful

**Comment by NagyZoltanPeter** [comment]
Agree, lessons learned. Therefore close this.

**Pull request closed without merging**
