### PR TITLE
chore: closing ping streams

### LINKED ISSUE #2462: chore: close stale ping connections
### Background
A node pings its peers every 2 minutes in https://github.com/waku-org/nwaku/blob/56ff30ca75100b06cb5157ae2655092b3051ec8c/waku/node/waku_node.nim#L1072-L1073
However the connections are never closed

We rely on libp2p's default connection limits. For example
```proc withMplex*(b: SwitchBuilder, inTimeout = 5.minutes, outTimeout = 5.minutes, maxChannCount = 200): SwitchBuilder```

If that's not set by libp2p (what has happened us with yamux), the number of connections grows indefinitely.
We should close unused connections ourselves.

### Acceptance criteria
Unused connections are deliberately closed

### PR DESCRIPTION
**Pull request by gabrielmer**
# Description

We're opening ping streams every 2 minutes but not closing them. This means we get an ever increasing amount of stale streams. Therefore, closing the stream after the ping.

# Changes

- [x] close ping stream after usage

## Testing
Tested it by calling https://github.com/waku-org/nwaku/blob/a37c9ba91158a90879a9e78f124a6e11e1900279/waku/node/peer_manager/peer_manager.nim#L655-L671 and https://github.com/waku-org/nwaku/blob/a37c9ba91158a90879a9e78f124a6e11e1900279/waku/node/peer_manager/peer_manager.nim#L673-L685

inside `keepaliveLoop()` and logging the outputs

The conclusions were:
- without calling `conn.close()`, the output of `getNumStreams()` grew indefinitely
- calling `conn.close()`, the output of `getNumStreams()` varied but was stable
- calling `conn.close()`did not affect the output of `connectedPeers()`, which means that indeed it didn't affect the physical connections

## Issue

closes #2462

### CODE REVIEW

**Review by NagyZoltanPeter — APPROVED** [review]
Good catch. Isn't this feature is disabled by default?

**Comment by gabrielmer** [comment]
> Good catch. Isn't this feature is disabled by default?

Yes! So the feature is disabled by default, but in `nwaku-compose` we do start the node with `keep-alive=true`

**Comment by AlbertoSoutullo** [comment]
> Yes! So the feature is disabled by default, but in `nwaku-compose` we do start the node with `keep-alive=true`

Wait, one question so I can understand this. Are you saying that this behavior were happening only if we had the `keep-alive` flag set to True?

**Review by alrevuelta — APPROVED** [review]
lgtm.

Was wondering why we were not seeing this in `waku_streams_peers` but just realized we only consider [waku protocols](https://github.com/waku-org/nwaku/blob/master/waku/node/peer_manager/waku_peer_store.nim#L79) (ping is excluded).

good catch

**Comment by gabrielmer** [comment]
> Wait, one question so I can understand this. Are you saying that this behavior were happening only if we had the `keep-alive` flag set to True?

Yes, if `keep-alive` is set to false then we wouldn't open those ping connections every 2 minutes that make the open connections to grow indefinitely

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks! :100: 
As a possible future optimization we should only `dial` once at the beginning and then keep using that connection on further pings

**Comment by AlbertoSoutullo** [comment]
> Yes, if `keep-alive` is set to false then we wouldn't open those ping connections every 2 minutes that make the open connections to grow indefinitely

Then I will need to doublecheck this in our simulations, because we are not using that flag...

**Pull request merged**
