### PR TITLE
chore(config): Deprecation of the 'topics' param

### PR DESCRIPTION
**Pull request by Ivansete-status**
# Description
This is for deprecating the `topics` param in favor of the `topic` one.

## How to test

1. From CLI:
   `./build/wakunode2 --topic="topic1" --topic="topic2" --config-file=cfg_node.txt`
   
   In this case, the CLI overrides the config file params.
   
2. From config file:
   `./build/wakunode2 --config-file=cfg_node.txt`

[cfg_node.txt](https://github.com/waku-org/nwaku/files/11769553/cfg_node.txt)

### CODE REVIEW

**Review by alrevuelta — APPROVED** [review]
thanks! lgtm

perhaps this is more explanatory? but indeed your example is also representative.
./build/wakunode2 --topics="topic1 topic2 topic3" (before)
./build/wakunode2 --topic="topic1" --topic="topic2" (after)

have we checked that all our 4 fleets use `topic` instead of `topics`?

**Comment by Ivansete-status** [comment]
Morning! Thanks @alrevuelta for the comment!
And yes, your examples are much more explicit :)

Hi @jakubgs , does the next implies that the `--topic` is being used in all the Nwaku fleets?
https://github.com/status-im/infra-role-nim-waku/blob/eed1a10ccea90c3b33af845ba54334530467a625/templates/docker-compose.yml.j2#L51

**Review by jm-clius — APPROVED** [review]
Thanks for this!

**Comment by jakubgs** [comment]
Any reason why this was merged and deployed without coordinating appropriate infra changes?
```
admin@node-01.do-ams3.status.test:~ % d
CONTAINER ID   NAMES      IMAGE                                    CREATED        STATUS
690e37d678b4   nim-waku   statusteam/nim-waku:deploy-status-test   21 hours ago   Restarting (1) 27 seconds ago
admin@node-01.do-ams3.status.test:~ % tail -n2 /var/log/docker/nim-waku/docker.log
2023-06-21T13:38:53.729173+00:00 docker/nim-waku[876]: Unrecognized option 'topics'#033[0m
2023-06-21T13:38:53.729193+00:00 docker/nim-waku[876]: Try #033[36mwakunode2 --help#033[0m for more information.
```
All of `status.test` is down right now.

image

**Pull request merged**
