### PR TITLE
chore: Adding -d:postgres flag when creating a Docker image for release and PRs

### PR DESCRIPTION
**Pull request by Ivansete-status**
# Description
The `-d:postgres` _Nim_ flag was added in order to not build the _Postgres_ archive driver when a new user wanted to compile the `wakunode` from the command line manually. However, we do want to have _Postgres_ support on each _Docker_ image, both in releases and in PRs.

# Changes

- [x] Addition of `-d:postgres` in `.github/workflows/container-image.yml`.
- [x] Addition of `-d:postgres` in `ci/Jenkinsfile.prs`.
- [x] Addition of `-d:postgres` in `ci/Jenkinsfile.release`.
- [x] Addition of `-d:postgres` in `.github/workflows/pre-release.yml`.
- [x] Addition of `-d:postgres` in `.github/workflows/release-assets.yml`.

### CODE REVIEW

**Comment by Ivansete-status** [comment]
Thanks @vpavlin for this recommendation https://github.com/waku-org/nwaku/pull/2076/commits/90be9162ec46edcc7846d054a55792260116cafd :rocket: !

**Review by vpavlin — APPROVED** [review]
I believe this covers all "release" assets - images and binaries + dev/test images built from PRs

One question though - why are you using `-d:postgres` and not `POSTGRES=1` like with `ci.yml`?

**Comment by Ivansete-status** [comment]
> One question though - why are you using `-d:postgres` and not `POSTGRES=1` like with `ci.yml`?

Thanks for the review!
The `POSTGRES=1` passed to the `make` has the same result, i.e. adding the `-d:postgres` as an additional `NIM_PARAMS`. This PR only introduces `-d:postgres` directly to make itself more consistent because, for e.g., the `ci/Jenkinsfile.release` only accepts `NIM_PARAMS`.

**Review by NagyZoltanPeter — APPROVED** [review]
Thank you! It looks ok!

**Pull request merged**
