### PR TITLE
chore: remove json rpc

### PR DESCRIPTION
**Pull request by alrevuelta**
# Description

⚠️ Completely removes the json-rpc api, removing also the following cli flags:
* `rpc`
* `rpcAddress`
* `rpcPort`
* `rpcAdmin`
* `rpcPrivate`

From now on, to interact with `nwaku` refer to the [REST API](https://github.com/waku-org/nwaku/blob/master/docs/api/rest-api.md).
Closes https://github.com/waku-org/nwaku/issues/2053

### CODE REVIEW

**Comment by Ivansete-status** [comment]
Thanks for this!

However, IMO, I think we first need to have a mature REST and I'm afraid we are not in that stage yet.
On the other hand, we will need to coordinate and inform infra about that deprecation.

IMO, the best strategy would be:
1. Complete REST and make sure the documentation and all endpoints work perfectly.
2. Inform infra about our intention of deprecating json-rpc
3. Merge this PR

**Comment by alrevuelta** [comment]
> Complete REST and make sure the documentation and all endpoints work perfectly.

@Ivansete-status mind being more actionable? whats missing in the rest API?

> Inform infra about our intention of deprecating json-rpc

done

**Comment by Ivansete-status** [comment]
> @Ivansete-status mind being more actionable? whats missing in the rest API?

Sure! These are the most relevant outstanding points, without considering bug issues.

Private Rest API - https://github.com/waku-org/nwaku/issues/2227
Reorganize RestApi specs for live documentation - https://github.com/waku-org/nwaku/issues/2120
Reorganize rest-api types - https://github.com/waku-org/nwaku/issues/2121
Allow to configure RLN via the REST API - https://github.com/waku-org/nwaku/issues/1985

As a reminder, REST tasks were deprioritized in favor of others.

@chair28980 - this is something that we could comment on in our next pm meeting and give more priority to that matter.

**Comment by alrevuelta** [comment]
> Private Rest API - https://github.com/waku-org/nwaku/issues/2227
Reorganize RestApi specs for live documentation - https://github.com/waku-org/nwaku/issues/2120
Reorganize rest-api types - https://github.com/waku-org/nwaku/issues/2121
Allow to configure RLN via the REST API - https://github.com/waku-org/nwaku/issues/1985

In order:
* 1. I see [admin rest](https://github.com/waku-org/nwaku/blob/master/waku/waku_api/rest/admin/handlers.nim) and [admin rpc](https://github.com/waku-org/nwaku/blob/master/waku/waku_api/jsonrpc/admin/handlers.nim) implement the same endpoints, which are `/admin/v1/peers` and `/admin/v1/filter/subscriptions`. What's missing there?
* Don't see how that's a blocker, isn't enough with [this](https://waku-org.github.io/waku-rest-api/)?
* Seems like a refactor to me, why blocker?
* No RLN endpoints are present neither in the json rpc, why would that be a blocker?

**Comment by alrevuelta** [comment]
Relevant
https://github.com/waku-org/pm/issues/125#issuecomment-1926727368

**Comment by Ivansete-status** [comment]
> * Lets move the conversations of this to [feat: HTTP REST API: Private API #2227](https://github.com/waku-org/nwaku/issues/2227)
> * Don't see how that's a blocker, isn't enough with [this](https://waku-org.github.io/waku-rest-api/)?
> * Seems like a refactor to me, why blocker?
> * No RLN endpoints are present neither in the json rpc, why would that be a blocker?

in order:

1.- Ok!

2.- 3.- 4.- 
I agree that these points seem not to be blockers at all but I'd like someone (me or another nwaku engineer) to invest some time in ensuring:
  - All endpoints work as expected and are aligned with the current JSON-RPC.
  - The OpenAPI docs are accurate.

On the other hand, we cannot deprecate JSON-RPC abruptly without proper notification to counterparties. i.e. we need to inform that we are starting to deprecate the JSON-RPC and keep this notification for at least two consecutive releases. In other words, we need to start informing other teams/projects to start using REST and once we make sure (assuming 2 releases is enough time) they can work well with REST, then it is fine to decommission JSON-RPC.

And btw, thanks again @alrevuelta for this initiative! I think is very interesting to have it completed!

---
@chair28980 @gabrielmer @NagyZoltanPeter - I've added a point for tomorrow's PM session to discuss it

**Comment by NagyZoltanPeter** [comment]
> > Private Rest API - #2227
This one is missing although it was not part of json-rpc so nothing outstanding.

> > Reorganize RestApi specs for live documentation - #2120
With new targets of go-waku, it will be easier, due to former msalignment between the two implementations.
Reorg is done in a separate repo: https://github.com/waku-org/waku-rest-api
We need to remove specs from nwaku and go-waku to let live them in one place.

> > Reorganize rest-api types - #2121
Yes, this is aiming a small refactoring.

> > Allow to configure RLN via the REST API - #1985
This one also new stuff.

> 
> In order:
> 
> * Lets move the conversations of this to [feat: HTTP REST API: Private API #2227](https://github.com/waku-org/nwaku/issues/2227)
> * Don't see how that's a blocker, isn't enough with [this](https://waku-org.github.io/waku-rest-api/)?
> * Seems like a refactor to me, why blocker?
> * No RLN endpoints are present neither in the json rpc, why would that be a blocker?

I see nothing blocking here in order to remove json-rpc.

**Comment by NagyZoltanPeter** [comment]
Btw: 
```rpcPrivate```
flag is not used anywhere.

**Comment by alrevuelta** [comment]
As agreed, we will announce the deprecation in the current release 0.25.0 and completely remove support in 0.26.0. This PR is blocked till then.

**Review by jakubgs — APPROVED** [review]
We will have to remove the `rpc.sh` script from the Ansible role:
https://github.com/status-im/infra-role-nim-waku/blob/master/templates/rpc.sh.j2

Possibly replace it with something similar that would allow us to get some common types of info via REST API, like version or number of peers, but that's trivial.

Also, the docs for REST API are very sparse, for example I see no info about `/admin/v1/peers` endpoint:
https://github.com/waku-org/nwaku/blob/master/docs/api/rest-api.md

I see something here:
https://github.com/waku-org/nwaku/blob/master/waku/waku_api/rest/admin/openapi.yaml

But I see no info about endpoint that returns node version.

**Comment by NagyZoltanPeter** [comment]
@jakubgs please note that API docs had moved and living live here: https://waku-org.github.io/waku-rest-api/#get-/debug/v1/info

**Comment by jakubgs** [comment]
I see, didn't know that. But if the docs exist there shouldn't the obsolete/outdated one in `docs/api` be removed?

Also, shouldn't we publish https://waku-org.github.io/waku-rest-api/ under https://rest-api.waku.org/ or https://api.waku.org/?

**Comment by jakubgs** [comment]
Here you go:
* https://github.com/status-im/infra-role-nim-waku/pull/25

**Comment by NagyZoltanPeter** [comment]
> I see, didn't know that. But if the docs exist there shouldn't the obsolete/outdated one in `docs/api` be removed?
> 
> Also, shouldn't we publish https://waku-org.github.io/waku-rest-api/ under https://rest-api.waku.org/ or https://api.waku.org/?

Yes, I agree we will need to find a more straightforward place for it instead of a gh pages hosted one.
But notice REST API works got de-prio in favor of other task.
For the doc reference page we will need to cross check any difference in order to remove specs from nwaku / go-waku repos.

**Review by SionoiS — APPROVED** [review]
Finally we're removing it! LGTM

**Comment by LordGhostX** [comment]
@NagyZoltanPeter, thanks for the ping 🫡

I removed references to the JSON-RPC API a long time ago in preference for the REST API. I'll take down the config section once it's released: https://docs.waku.org/guides/nwaku/config-options#json-rpc-config

**Comment by alrevuelta** [comment]
With https://github.com/status-im/infra-role-nim-waku/pull/25 merged and js-waku-node CI job ✅ , merging. js-waku-node-optional is a known flaky one.

**Pull request merged**
