### PR TITLE
chore: automatically add new issues and PRs to project board

### PR DESCRIPTION
**Pull request by fryorcraken**

### CODE REVIEW

**Comment by Ivansete-status** [comment]
Thanks for this @fryorcraken ! May kindly elaborate on the goal of this PR?

**Comment by fryorcraken** [comment]
This is so that new issues are automatically added to the Waku GitHub project board. Cc @jm-clius . We had a recent discussion in discord.

**Comment by Ivansete-status** [comment]
> This is so that new issues are automatically added to the Waku GitHub project board. Cc @jm-clius . We had a recent discussion in discord.

Okay perfect, but this already works correctly, isn't it? When a new issue is submitted it appears under the "No Status" column:

image

**Comment by fryorcraken** [comment]
ok :)

**Pull request closed without merging**
