### PR TITLE
chore: waku_metrics - change log interval from 30'' to 10'

### PR DESCRIPTION
**Pull request by Ivansete-status**
## Description
Simple PR to change the log cadence as per our last PM meeting.

It changes the frequency of "Total *" logs (metrics logs) from 30 seconds to 10 minutes.

### CODE REVIEW

**Review by gabrielmer — APPROVED** [review]
Thank you!

**Review by NagyZoltanPeter — APPROVED** [review]
Super fast reaction! Thank you. :-)

**Review by alrevuelta — COMMENTED** [review]
can we merge some lines as well? here and in `getRlnMetricsLogger`

something like this. That /5 the amount of logs without impacting the frequency.
```
info "Connected peers", storePeers=storePeers, pxPeers=pxPeers, lightpushPeers=lightpushPeers, filterPeers=filterPeers.
```

which btw, might be a peermanager job. but that's for another day.

and well, not relevant if the protocol is not enabled (eg with lp disabled will print always 0) but also, ok by now.

**Review by jm-clius — APPROVED** [review]
LGTM. :)

**Comment by Ivansete-status** [comment]
@alrevuelta - I'll submit a separate PR with your proposal, https://github.com/waku-org/nwaku/pull/2428#pullrequestreview-1878464481

**Pull request merged**
