### PR TITLE
chore: fix typos 

### PR DESCRIPTION
**Pull request by omahs**
chore: fix typos

### CODE REVIEW

**Review by SionoiS — APPROVED** [review]
Very nice. Thank you!

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks for it! :100:

**Comment by Ivansete-status** [comment]
Hey @omahs ! Thanks for this PR but we need all the commits to be properly signed.

The following is an example of a good-signed commit:
image

Cheers

**Comment by Ivansete-status** [comment]
Morning @omahs !
Your commits aren't signed yet.
See for example, the difference between yours and mine commits:
image

The following can help achieving signing commits, it is pretty straightforward :)
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

Cheers!

**Comment by omahs** [comment]
@Ivansete-status I'm sorry I couldn't get my GPG key to work, I had to make another branch 😓

**Pull request closed without merging**
