### PR TITLE
chore: not allowing tcp-port 0 input  by the user

### PR DESCRIPTION
**Pull request by gabrielmer**
# Description

When the user chooses port 0, the node's published port is 0. However, that's not the port that we are getting bound to by the kernel.
Therefore, to avoid inconsistencies and imprecisions, we won't allow the user to choose port 0. Either the default port or a port explicitly chosen by the user will be used, avoiding non-deterministic outcomes.

# Changes

- [x] Throwing an error in case port 0 is selected by the user
- [x] Updating tests that configure Waku nodes with port 0 as default, and change them so they use our current default 60000 port

## Issue

closes [#1883](https://github.com/waku-org/nwaku/issues/1883)

### CODE REVIEW

**Comment by gabrielmer** [comment]
> Port 0 allows the system to pick a port, which is a feature in many cases

Yes, the main issue here is us publishing the 0 port when that's not really the port allocated by the kernel during runtime.
The final solution we aim for is to update all our internal data structures to reflect the port chosen by the system.

Currently, `WakuNode` is getting built and filled before the port binding happens, so updating all the internal data structures consistently with the actual port might require some major refactoring.
We agreed that initially, restricting the user from choosing port 0 can be our initial solution to avoid this situation. So the user can either use the default port, or choose one explicitly themselves.

@arnetheduck What do you think about it? Are there cases in which this could be problematic?

**Comment by arnetheduck** [comment]
Not sure - seems easier to just get it done than to confuse users for a while and then get it done - that said, I'm not familiar with the scope of refactoring needed - as long as there's a plan, sgtm, though it's always sad when applications are missing this little piece of convenience (specially because we run discovery and auto-nat-config and a number of other surrounding services all built for the purpose of not locking a particular port)

**Comment by gabrielmer** [comment]
> Not sure - seems easier to just get it done than to confuse users for a while and then get it done - that said, I'm not familiar with the scope of refactoring needed - as long as there's a plan, sgtm, though it's always sad when applications are missing this little piece of convenience (specially because we run discovery and auto-nat-config and a number of other surrounding services all built for the purpose of not locking a particular port)



> Not sure - seems easier to just get it done than to confuse users for a while and then get it done - that said, I'm not familiar with the scope of refactoring needed - as long as there's a plan, sgtm, though it's always sad when applications are missing this little piece of convenience (specially because we run discovery and auto-nat-config and a number of other surrounding services all built for the purpose of not locking a particular port)

True, makes sense - it might just confuse users. 
The rationale for postponing it was simply because of inexperience - we felt we needed to know better the codebase in order to make this change properly and efficiently. In the future it should be an easier task to handle for the team. As it wasn't seen enough as a priority for the resources it might currently take, we thought of the temporary solution of not allowing the user to choose the 0 port.
At the end of the day, it is just a matter of resources and priorities. But we might have underestimated its importance, I'll double check and discuss again how we should proceed with this :)

**Comment by gabrielmer** [comment]
After discussing the issue deeper, we decided not to move forward with approach. The plan is to work is to allow port 0 to be chosen by the user and properly handle the kernel's port selection. Therefore, closing this PR.
Opened issue #2042 for tracking

**Pull request closed without merging**
