### PR TITLE
chore: postgres_driver limit max num hashes to 100

### PR DESCRIPTION
**Pull request by Ivansete-status**
Limit the query by hashes to 100 hashes per query

### CODE REVIEW

**Review by gabrielmer — APPROVED** [review]
LGTM! Thank you!

**Review by SionoiS — APPROVED** [review]
Nice one!

**Review by richard-ramos — APPROVED** [review]
LGTM.
I do have a question tho:

Do you think it makes sense to add a condition that requires the pagingSize to match the value of `hashes.len` ?

IMO it is probably wasteful to do paging when you are querying records via array of hashes, since then the DB will have to do this effort of filtering the data, to then just ignore the records you don't need. 

i.e.:  Assuming you are interested in retrieving 30 message hashes and have a limit of 10, this is probably less efficient:
```
-- First request
SELECT m1.* 
FROM messages m1 
INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
WHERE m2.message_hash IN (30 message hashes go here)
LIMIT 10

-- Second request
SELECT m1.* 
FROM messages m1 
INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
WHERE m2.message_hash IN (30 message hashes go here)
AND m2.message_hash >= SOME_CURSOR_HERE
LIMIT 10

-- Third request
SELECT m1.* 
FROM messages m1 
INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
WHERE m2.message_hash IN (30 message hashes go here)
AND m2.message_hash >= SOME_CURSOR_HERE
LIMIT 10
```

Compared to do the paging locally:
```
-- First request
SELECT m1.* 
FROM messages m1 
INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
WHERE m2.message_hash IN (first 10 message hashes go here)
LIMIT 10

-- Second request
SELECT m1.* 
FROM messages m1 
INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
WHERE m2.message_hash IN (message hashes from 11 to 20 go here)
LIMIT 10

-- Third request
SELECT m1.* 
FROM messages m1 
INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
WHERE m2.message_hash IN (message hashes from 21 to 30 go here)
LIMIT 10
```

**Review by kaichaosun — APPROVED** [review]

**Comment by Ivansete-status** [comment]
> LGTM. I do have a question tho:
> 
> Do you think it makes sense to add a condition that requires the pagingSize to match the value of `hashes.len` ?
> 
> IMO it is probably wasteful to do paging when you are querying records via array of hashes, since then the DB will have to do this effort of filtering the data, to then just ignore the records you don't need.
> 
> i.e.: Assuming you are interested in retrieving 30 message hashes and have a limit of 10, this is probably less efficient:
> 
> ```sql
> -- First request
> SELECT m1.* 
> FROM messages m1 
> INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
> WHERE m2.message_hash IN (30 message hashes go here)
> LIMIT 10
> 
> -- Second request
> SELECT m1.* 
> FROM messages m1 
> INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
> WHERE m2.message_hash IN (30 message hashes go here)
> AND m2.message_hash >= SOME_CURSOR_HERE
> LIMIT 10
> 
> -- Third request
> SELECT m1.* 
> FROM messages m1 
> INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
> WHERE m2.message_hash IN (30 message hashes go here)
> AND m2.message_hash >= SOME_CURSOR_HERE
> LIMIT 10
> ```
> 
> Compared to do the paging locally:
> 
> ```sql
> -- First request
> SELECT m1.* 
> FROM messages m1 
> INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
> WHERE m2.message_hash IN (first 10 message hashes go here)
> LIMIT 10
> 
> -- Second request
> SELECT m1.* 
> FROM messages m1 
> INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
> WHERE m2.message_hash IN (message hashes from 11 to 20 go here)
> LIMIT 10
> 
> -- Third request
> SELECT m1.* 
> FROM messages m1 
> INNER JOIN messages_lookup m2 ON m1.message_hash = m2.messagehash
> WHERE m2.message_hash IN (message hashes from 21 to 30 go here)
> LIMIT 10
> ```

Thanks for the comment!
I think it is sensible what you suggest. Shall it require adaptations from the app client as well?

**Pull request merged**
